apiVersion: v1
kind: Service
metadata: 
  name: nginx 
spec:
  clusterIP: 10.100.0.50
  selector:
    role: nginx-server
  ports:
  - port: 80 
    targetPort: 80 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-server 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: nginx-server
    spec:
      containers:
      - name: nginx 
        image: caseydavenport/nginx 
