kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: nginx-service
spec:
  podSelector:
    matchLabels:
      role: nginx-server
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: getter
      ports:
        - protocol: TCP
          port: 80