apiVersion: v1
kind: ReplicationController
metadata:
  name: getter
spec:
  replicas: 0
  selector:
    role: getter
  template:
    metadata:
      labels:
        role: getter
    spec:
      containers:
      - name: getter
        image: __CLUSTER_PREFIX__-master:5000/scale-tester
        env:
        - name: TIMEOUT
          value: ".1"
        - name: SLEEPTIME
          value: "0"
